### ISSUE TITLE
Remote Live logs after '\n' and not on buffer_size

### ISSUE THREAD

**Issue by ricleal** [ornl-ndav/django-remote-submission#14]
We have:

https://github.com/ornl-ndav/django-remote-submission/blob/master/django_remote_submission/remote.py#L149

```python
        channel.exec_command(command)
        while True:
            current_time = now()
            if channel.recv_ready():
                output = channel.recv(1024).decode('utf-8')
                stdout_handler(current_time, output)

            if channel.recv_stderr_ready():
                output = channel.recv_stderr(1024).decode('utf-8')
                stderr_handler(current_time, output)
```

i.e., logs are flushed after 1024 bytes. Can we flush them after `\n`?

See `paramiko-expect` tail function:

https://github.com/fgimian/paramiko-expect/blob/943630ac499284e6441854a9c4ae1e04301bfdd9/paramiko_expect.py#L213

`buffer = self.channel.recv(1)` and search for `\n`.

Is it going to be too slow?

**Comment by player1537** [comment]
I think this should work if you run Python as `python -u foo.py`, which just means we need the `{ "arguments": ["-u"] }` in the fixture.
