### ISSUE TITLE
Look into way to synchronize setup.py and requirements.txt

### ISSUE THREAD

**Issue by player1537** [ornl-ndav/django-remote-submission#21]
* Django Remote Submission version: 0.6.0
* Django version: n/a
* Python version: n/a
* Operating System: n/a

### Description

While making changes to fix #11, I realized that it's very easy for the requirements that `setup.py` lists to become out of sync with the ones in `requirements.txt`. I noticed that we've actually been missing Django Rest Framework in `setup.py` for a while.

I know some other projects use some code to parse the requirements file into `install_requires` to keep them in sync. I'm not sure the tradeoffs, though, so I'll need to look into that some.

I'm also not clear what the best method is to have an optional dependency in `setup.py`. For example, the library doesn't require Celery (because it can use some fallback behavior), but it does support Celery.

**Comment by djmitche** [comment]
Setup can support optional dependencies (via `extras_require` - [here](https://github.com/mozilla/build-fwunit/blob/master/setup.py) is an example in a repo of mine).  Why not *only* use `setup.py` and just remove `requirements.txt`?

**Comment by ricleal** [comment]
That's the way I did it in `setup.py` and `pip 9.0.1`:

```python
from pip.req import parse_requirements
#
install_reqs = parse_requirements('requirements.txt', session='hack')
# reqs is a list of requirement
# e.g. ['django==1.5.1', 'mezzanine==1.4.6']
reqs = [str(ir.req) for ir in install_reqs]
#
setup(
  # stuff,
  install_requires=reqs,
  # stuff
)
```
It will be pushed to `dev` soon.
