### ISSUE TITLE
Update doc for make release (upload to pypi)

### ISSUE THREAD

**Issue by ricleal** [ornl-ndav/django-remote-submission#9]
Where is the user defined when uploading to pypi `make release`?
Our user is `ornl.ndv`.

We need some small doc about how to release:
- username
- version change

**Comment by player1537** [comment]
I will work on a document for this and verify that everything works.

For now, I believe the way I have been doing the whole add feature, test, merge, release process is:

1. Create a branch for the feature off of master.
1. Make the necessary changes.
1. Add tests to illustrate the desired results of the code that was added.
1. Run `make test` to make sure I haven't broken anything.
1. When I'm confident it's working with `make test`, also run it with `make test-all`.
1. Commit changes and push to the feature branch.
1. Double check that the tests work on Travis.
1. Make sure the documentation is correct still.
1. Run `make docs` to ensure that the docs build correctly (including the doctests).
1. Commit again and make sure it works on Travis.
1. Update the `HISTORY.rst` file in the root directory (which still needs to be integrated into the docs, but I'll do that soon.)
1. Run `bumpversion minor` (or `patch` or `major`) to update the versions in all affected files (I think you might need to specify the previous version or something? That's one thing I'll need to double check.)
1. Make a pull request on GitHub and merge (Again, Travis will double check that the tests are working).
1. Once it's merged, switch back to master (pull again, too) and run `make release` which will ask for your username and password for PyPI.

**Comment by player1537** [comment]
I just about have this document finished. Once I fix #7 and the associated pull request, I'll be able to merge those into master, and then add the section on how to release to PyPI (since I'll have a chance to test that it's working correctly).
